// Copyright (C) 2002-2012 Nikolaus Gebhardt
// This file is part of the "Irrlicht Engine".
// For conditions of distribution and use, see copyright notice in irrlicht.h

#ifndef __BUILD_IN_FONT_H_INCLUDED__
#define __BUILD_IN_FONT_H_INCLUDED__

#include "IrrCompileConfig.h"
#ifdef _IRR_COMPILE_WITH_GUI_

// header file generated by Bin2H, copyright 2002 by N.Gebhardt.
// Bin2H is Freeware. Download it freely from www.code3d.com.
// for the source bitmap, see builtInFont.bmp

namespace irr
{
namespace gui
{
#ifdef _IRR_COMPILE_WITH_BMP_LOADER_
    extern unsigned char BuiltInFontData[];
	extern unsigned int  BuiltInFontDataSize;
    
#else // !defined(_IRR_COMPILE_WITH_BMP_LOADER_)

	// built-in font cannot be loaded if there is no BMP loader
	unsigned char*  BuiltInFontData     = NULL;
	unsigned int    BuiltInFontDataSize = 0;

#endif
} // end namespace gui
} // end namespace irr

#endif // _IRR_COMPILE_WITH_GUI_

#endif

